version: "3"

services:
  blockagebot:
    container_name: VREF-Server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    restart: always