name: Create swagger documentation
on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Generate Swagger schema
        run: npm run generate:swagger

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: ./build/swagger.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Swagger UI Artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./swagger-ui

  publish:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

