name: Deploy Production Build
on:
    push:
        tags: v*
    workflow_dispatch:


jobs:
    call-build:
        uses: ./.github/workflows/build.yml
        with:
            tag: ${{ github.ref_name }}
    deploy:
        runs-on: self-hosted
        needs: call-build
        steps:
            - name: Stop old container
              continue-on-error: true
              run: |
                docker stop -t 10 vref-prod &&\
                docker container rm vref-prod

            - name: Start new container
              run: docker run -d -p 3000:3000 --restart always --name vref-prod vref-server:${{ github.ref_name }}